"""del namePath column

Revision ID: 3101f1abc352
Revises: edeb58990dba
Create Date: 2023-04-24 15:21:22.739278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3101f1abc352'
down_revision = 'edeb58990dba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audiofile', 'namePath')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiofile', sa.Column('namePath', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
