"""Database creationss

Revision ID: 918a518e2a5c
Revises: 
Create Date: 2023-04-24 14:58:29.738288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918a518e2a5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audiofile')
    # ### end Alembic commands ###
