"""add index fo id

Revision ID: ab5366353576
Revises: 3101f1abc352
Create Date: 2023-04-24 16:05:41.639458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5366353576'
down_revision = '3101f1abc352'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audiofile_id'), 'audiofile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audiofile_id'), table_name='audiofile')
    # ### end Alembic commands ###
