"""add namePath column

Revision ID: edeb58990dba
Revises: 918a518e2a5c
Create Date: 2023-04-24 15:19:13.315863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edeb58990dba'
down_revision = '918a518e2a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiofile', sa.Column('namePath', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audiofile', 'namePath')
    # ### end Alembic commands ###
